import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* {children} */}
          <header className="bg-slate-900 text-white p-4 text-center">
            {/* Welcome to NextJS 15 Crash Course */}
            <Navigation />
          </header>

          {children}

          <footer className="bg-slate-900 text-white p-4 text-center">
            © Copyrights | Chinmay Kaitade
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
